force-app/main/default/objects/Contribution__c/Contribution__c.object-meta.xml
<CustomObject>
    <label>Contribution</label>
    <nameField>
        <label>Contribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contribution__c/fields/Advocacy__c.field-meta.xml
<CustomField>
    <fullName>Advocacy__c</fullName>
    <formula>IF( INCLUDES( Pillars__c , &quot;Advocacy&quot;),1,0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Advocacy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meets Expectations</fullName>
            </value>
            <value>
                <fullName>Exceeds Expectations</fullName>
            </value>
            <value>
                <fullName>Does Not Meet Expectations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contributions</relationshipLabel>
    <relationshipName>Contributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <formula>IF( INCLUDES( Pillars__c , &quot;Expertise&quot;), 1, 0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expertise</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feedback</label>
    <referenceTo>Feedback__c</referenceTo>
    <relationshipLabel>Contributions</relationshipLabel>
    <relationshipName>Contributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Generosity__c.field-meta.xml
<CustomField>
    <fullName>Generosity__c</fullName>
    <formula>IF( INCLUDES( Pillars__c , &quot;Generosity&quot;) , 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Generosity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Leadership__c.field-meta.xml
<CustomField>
    <fullName>Leadership__c</fullName>
    <formula>IF( INCLUDES( Pillars__c , &quot;Leadership&quot;) , 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leadership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Pillars__c.field-meta.xml
<CustomField>
    <fullName>Pillars__c</fullName>
    <label>Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expertise</fullName>
            </value>
            <value>
                <fullName>Generosity</fullName>
            </value>
            <value>
                <fullName>Leadership</fullName>
            </value>
            <value>
                <fullName>Advocacy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Designation__c/Designation__c.object-meta.xml
<CustomObject>
    <label>Designation</label>
    <nameField>
        <label>Designation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Designation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Designations</relationshipLabel>
    <relationshipName>Designations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/Advocacy__c.field-meta.xml
<CustomField>
    <fullName>Advocacy__c</fullName>
    <label>Advocacy</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Advocacy_Rating__c.field-meta.xml
<CustomField>
    <fullName>Advocacy_Rating__c</fullName>
    <label>Advocacy (Rating)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Expertise_Rating__c.field-meta.xml
<CustomField>
    <fullName>Expertise_Rating__c</fullName>
    <label>Expertise (Rating)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Generosity__c.field-meta.xml
<CustomField>
    <fullName>Generosity__c</fullName>
    <label>Generosity</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Generosity_Rating__c.field-meta.xml
<CustomField>
    <fullName>Generosity_Rating__c</fullName>
    <label>Generosity (Rating)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Leadership__c.field-meta.xml
<CustomField>
    <fullName>Leadership__c</fullName>
    <label>Leadership</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Leadership_Rating__c.field-meta.xml
<CustomField>
    <fullName>Leadership_Rating__c</fullName>
    <label>Leadership (Rating)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Nominator__c.field-meta.xml
<CustomField>
    <fullName>Nominator__c</fullName>
    <label>Nominator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Feedback__c/recordTypes/Feedback.recordType-meta.xml
<RecordType>
    <fullName>Feedback</fullName>
    <active>true</active>
    <label>Feedback</label>
</RecordType>

force-app/main/default/classes/DesignationController.cls
public with sharing class DesignationController {
    @AuraEnabled(cacheable=true)
    public static Map<Integer , List<Contribution__c>>  getContributionsAssociatedWithDesignation(String designationId){
        List<Designation__c> designationList  = [Select Id, Name, Contact__r.LastName, Contact__r.Id FROM Designation__c WHERE Id= :designationId ];
        Set<Id> contactIdSet = new Set<Id>();
        for(Designation__c designation : designationList) {
            contactIdSet.add(designation.Contact__r.Id);
        }

        List<Contribution__c> contributionList = [SELECT Id,Name, Expertise__c, Generosity__c,Pillars__c, Leadership__c, Advocacy__c, Assessment__c, Date__c, Details__c, Contact__r.Id 
                FROM Contribution__c 
                WHERE Contact__r.Id IN :contactIdSet ];

        Map<Integer , List<Contribution__c>>  yearToContributionMap = new Map<Integer, List<Contribution__c>>();
        for(Contribution__c contribution : contributionList){
            if (yearToContributionMap.containsKey(contribution.Date__c.year())) {
                yearToContributionMap.get(contribution.Date__c.year()).add(contribution);
            } else {
                List<Contribution__c> newContributionListList = new List<Contribution__c>();
                newContributionListList.add(contribution);
                yearToContributionMap.put(contribution.Date__c.year(), newContributionListList);
            }
        }     
        
        return yearToContributionMap;
    }

    @AuraEnabled(cacheable=true)
    public static Map<Integer, List<Feedback__c>> getSelfFeedbackAssociateWithDesignation(String designationId){
        List<Designation__c> designationList  = [Select Id,Contact__r.Id FROM Designation__c WHERE Id= :designationId ];
        Set<Id> contactIdSet = new Set<Id>();
        for(Designation__c designation : designationList) {
            contactIdSet.add(designation.Contact__r.Id);
        }

        List<Feedback__c> feedbackList = [SELECT Id,Date__c,RecordType.Name, Nominator__r.Id,Nominator__r.Name
                FROM Feedback__c 
                WHERE Nominator__r.Id IN :contactIdSet AND RecordType.Name='Self-Feedback'];

        Map<Integer , List<Feedback__c>>  yearToFeedbackMap = new Map<Integer, List<Feedback__c>>();
        for(Feedback__c feedback : feedbackList){
            if (yearToFeedbackMap.containsKey(feedback.Date__c.year())) {
                yearToFeedbackMap.get(feedback.Date__c.year()).add(feedback);
            } else {
                List<Feedback__c> newFeedbackList = new List<Feedback__c>();
                newFeedbackList.add(feedback);
                yearToFeedbackMap.put(feedback.Date__c.year(), newFeedbackList);
            }
        }     
        
        return yearToFeedbackMap;
    }

    @AuraEnabled(cacheable=true)
    public static Map<Integer, List<Feedback__c>>  getFeedbackAssociateWithDesignation(String designationId){
        Id contactId  = [Select Id,Contact__r.Id FROM Designation__c WHERE Id= :designationId limit 1].Contact__r.Id;

        List<Feedback__c> feedbackList = [SELECT Id,Date__c,RecordType.Name,Advocacy_Rating__c,Expertise_Rating__c,Generosity_Rating__c,Leadership_Rating__c, Nominator__r.Id,Nominator__r.Name
                FROM Feedback__c 
                WHERE Nominator__r.Id = :contactId AND RecordType.Name='Feedback'];

        Map<Integer , List<Feedback__c>>  yearToFeedbackMap = new Map<Integer, List<Feedback__c>>();
        for(Feedback__c feedback : feedbackList){
            if (yearToFeedbackMap.containsKey(feedback.Date__c.year())) {
                yearToFeedbackMap.get(feedback.Date__c.year()).add(feedback);
            } else {
                List<Feedback__c> newFeedbackList = new List<Feedback__c>();
                newFeedbackList.add(feedback);
                yearToFeedbackMap.put(feedback.Date__c.year(), newFeedbackList);
            }
        }     
        
        return yearToFeedbackMap;
    }
}