force-app/main/default/objects/Account/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultant__c/Consultant__c.object-meta.xml
<CustomObject>
    <label>Consultant</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Consultant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultant__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consultants</relationshipLabel>
    <relationshipName>Consultants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Exercise3.cls
public with sharing class Exercise3 {
    // returns all names of the consultants working for that employer as a list
    public static List<Consultant__c> getConsultantsToEmployer(ID accountId) {
        List<Consultant__c> consultantsList = [SELECT  Name FROM Consultant__c WHERE Employer__r.Id = :accountId];
        return consultantsList;
    }

    public static Map<Account, Set<Id>> getEmployerAndConsultants(){
       Map<Account, Set<Id>> employerConsultantMap = new Map<Account, Set<Id>>();
        List<Account> accountList=[Select Id, (Select Id from Consultants__r) from Account where Id IN (Select Employer__c from Consultant__c)];
        Set<Id> ConsultantIdSet;
        for(Account account:accountList){
            consultantIdSet = new Set<Id>();
            for(Consultant__c consultant:account.Consultants__r){
                ConsultantIdSet.add(consultant.Id);
            }
            employerConsultantMap.put(account, consultantIdSet);
        }
        //for(Account acc: employerConsultantMap.keySet()){
            //System.debug('Id-->' + acc.Id + 'set'+ employerConsultantMap.get(acc));
       //}
        return employerConsultantMap;
    }

    public static Integer getWorkingDaysBetween(Date startDate, Date endDate) {
        Integer workingDays = 0;
        Integer daysBetween = startDate.daysBetween(endDate);
        
        for (Integer i = 0; i < daysBetween; i++) {
            DateTime currentDate = (DateTime)startDate.addDays(i);
            if (!currentDate.format('E').equals('Sat') && !currentDate.format('E').equals('Sun')) {
                workingDays++;
            }
        }
        
        return workingDays; 
    }
}